--Schema esquema2

-- Table t1
CREATE TABLE t1  
(id INTEGER PRIMARY KEY AUTOINCREMENT,  c1 TEXT);

-- Table t2
CREATE TABLE t2  
(id INTEGER PRIMARY KEY AUTOINCREMENT,  c2 INTEGER);

-- Table t3
CREATE TABLE t3  
(id INTEGER PRIMARY KEY AUTOINCREMENT,  c3 REAL, c4 INTEGER);
